config/routes.rb
Rails.application.routes.draw do
  root 'twitter#index'
  get '/search' => 'twitter#search', as: :search
  get '/load_more' => 'twitter#load_more', as: :load_more
  get '/recent' => 'twitter#get_recents', as: :recent

end

app/models/tweet.rb
class Tweet < OpenStruct

  def media
    entities['media'].present? ? entities['media'] :[]
  end

  def screen_name
    user['screen_name']
  end

  def profile_image
    user['profile_image_url']
  end

end

app/models/twitter_client.rb
class TwitterClient
  
  attr_reader :tweets, :next_query
 
  BASE_URL = "https://api.twitter.com/1.1/search/tweets.json"
 
  def initialize(api_key, api_secret, token, token_secret)
    @consumer_key ||= OAuth::Consumer.new api_key, api_secret
    @access_token ||= OAuth::Token.new token, token_secret
  end
  
  def search(q = nil)
    address = URI("#{BASE_URL}#{q}")
  
    request(address)
  end
 
  private 
    
  def request(address)
    request = Net::HTTP::Get.new address.request_uri
    http             = Net::HTTP.new address.host, address.port
    http.use_ssl     = true
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    request.oauth! http, @consumer_key, @access_token
    http.start
    response = http.request request
      
    case response.code
      when '200'
        resp = JSON.parse(response.body)
        @tweets = resp['statuses'].map{ |tweet| Tweet.new(tweet)}
        @next_query = resp['search_metadata']['next_results']
      else
        @tweets = []
    end
    @tweets
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :store_location
  before_action :configure_permitted_parameters, if: :devise_controller?

	def store_location
	  # store last url - this is needed for post-login redirect to whatever the user last visited.
	  return unless request.get? 
	  if (request.path != "/users/sign_in" &&
	      request.path != "/users/sign_up" &&
	      request.path != "/users/password/new" &&
	      request.path != "/users/password/edit" &&
	      request.path != "/users/confirmation" &&
	      request.path != "/users/sign_out" &&
	      request.path != "/" &&
	      !request.xhr?) # don't store ajax calls
	    session[:previous_url] = request.fullpath 
	  end
	end

  def after_sign_in_path_for(resource)
  	session[:previous_url] || posts_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :username, :location, :description, :email, :password, :password_confirmation) }
  end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
  def index
  end

  def search
    query = params[:query].present? ? params[:query] : "?q=#{params[:q]}&count=10"
    @tweets = twitter_client.search(query)
    puts @tweets
    @next_query = twitter_client.next_query
     if params[:q].present?
      recent << params[:q].to_s unless recent.include?(params[:q])
     end
  end  

  private

  def recent
    session[:recent] ||=[]
  end

  def twitter_client
    @twitter_client ||=TwitterClient.new(API_KEY, API_SECRET, TOKEN, TOKEN_SECRET)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitter_helper.rb
require 'twitter-text'
module TwitterHelper

  include Twitter::Autolink

  def twitter_text(tweet)
    text = tweet['text']
    text = auto_link(text)
    text ? text.html_safe : ''
  end
  def profile_url(screen_name)
    "https://twitter.com/#{screen_name}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%=yield %>
  </div>
  
<%= yield :javascripts %>

</body>
</html>

app/views/twitter/_autocomplete.js.erb
var recentSearch = <%= session[:recent].to_json.html_safe %>;
$('#q').autocomplete({

  minLength: 1,
  source: recentSearch,
  
  focus: function(event, ui) {
    $('#q').val(ui.item.value);
    return false;
  },

  select: function(event, ui) {

  $('#q').val(ui.item.value);
    return false;
  }
  
});

app/views/twitter/_load_more.html.erb
<% if next_query.present? %>
  <%= link_to 'Show more', search_path(query: next_query), remote: true %>
<% else %>
  <p>No results</p>
<% end %>  

app/views/twitter/_tweet.html.erb
<div class="tweet">
  <%= image_tag tweet.profile_image, width: 48, height: 48,  class: 'avatar' %>
  <%= link_to "@#{tweet.screen_name}", profile_url(tweet.screen_name), target: '_blank'%>
  <%= twitter_text(tweet) %>
  
  <% tweet.media.each do |media| %>
    <%= link_to media['expanded_url'], target: '_blank' do %>
      <%= image_tag media['media_url'], class: 'attach_img' %>
    <% end %>
  <% end %>
</div> 

app/views/twitter/index.html.erb
<div class="header">
  <%= image_tag 'twitter.png', width: 70, height: 70, alt: "twitter bird"%>
  <h1>Twitter</h1>
</div>
<%= form_tag search_path, method: :get, remote: true, class: "form-inline", :html => {:'data-type' => 'js'} do %>
  <%= text_field_tag :q, nil, placeholder: "Type something...", class: "search_bar" %>
  <%= submit_tag("Search", class:"search_submit")%>
<% end %>

<div class="tweets"></div>
<div class="load_more"></div>

<% content_for(:javascripts) do %>
  <script> 
    <%= render partial: "autocomplete.js.erb" %>
  </script>
<% end %>

app/views/twitter/search.js.erb
<% unless params[:query].present? %>
  $('.tweets').html('');
<% end %>

<% @tweets.each do |t| %>
  $('.tweets').append("<%= escape_javascript render(:partial => 'tweet', :locals => { :tweet => t }) %>");
<% end %>

$('.load_more').html("<%= escape_javascript render(:partial => 'load_more', :locals => { :next_query => @next_query}) %>");

<%= render partial: "autocomplete" %>